# Generated by Django 5.1.3 on 2024-11-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0018_auto_20210507_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='elearn.course'),
        ),
    ]
